apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-mysql-deployment
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers:
        - image: mysql:5.7
          imagePullPolicy: Always
          name: mysql
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user-password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
          envFrom:
          - configMapRef:
              name: mysql-configmap
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: phonebook-pv-claim