apiVersion: v1
kind: Service
metadata:
  name: result-server-service
spec:
  type: NodePort
  selector:
    app: phonebook-result-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002    
  